<?php
/**
 * @file
 * Migrations.
 */

// @codingStandardsIgnoreStart
return array (
  'api' => 2,
  'groups' =>
  array (
    'core' =>
    array (
      'title' => 'Core Entities',
    ),
    'doj' =>
    array (
      'title' => 'DOJ - Department of Justice',
    ),
    'afp' =>
    array (
      'title' => 'Asset Forfeiture Program',
    ),
    'atr' =>
    array (
      'title' => 'Antitrust Division',
    ),
    'atr-espanol' =>
    array (
      'title' => 'División Antimonopolios en español',
    ),
    'eousa' =>
    array (
      'title' => 'EOUSA - Executive Office for United States Attorneys',
    ),
    'usao' =>
    array (
      'title' => 'USAO - United States Attorneys Office',
    ),
    'usao-id' =>
    array (
      'title' => 'District of Idaho',
    ),
    'usao-mdla' =>
    array (
      'title' => 'Middle District of Louisiana',
    ),
    'ust-regions' =>
    array (
      'title' => 'U.S. Trustee Program Regions and Offices',
    ),
    'eoir' =>
    array (
      'title' => 'Executive Office for Immigration Review',
    ),
    'usao-sdin' =>
    array (
      'title' => 'Southern District of Indiana',
    ),
    'usao-wdla' =>
    array (
      'title' => 'Western District of Louisiana',
    ),
    'usao-md' =>
    array (
      'title' => 'District of Maryland',
    ),
    'usao-ndny' =>
    array (
      'title' => 'Northern District of New York',
    ),
    'usao-sc' =>
    array (
      'title' => 'District of South Carolina',
    ),
    'usao-wdmi' =>
    array (
      'title' => 'Western District of Michigan',
    ),
    'usao-ndms' =>
    array (
      'title' => 'Northern District of Mississippi',
    ),
    'usao-wdwa' =>
    array (
      'title' => 'Western District of Washington',
    ),
    'usao-nv' =>
    array (
      'title' => 'District of Nevada',
    ),
    'usao-ne' =>
    array (
      'title' => 'District of Nebraska',
    ),
    'usao-or' =>
    array (
      'title' => 'District of Oregon',
    ),
    'usao-edwa' =>
    array (
      'title' => 'Eastern District of Washington',
    ),
    'usao-ak' =>
    array (
      'title' => 'District of Alaska',
    ),
    'usao-nd' =>
    array (
      'title' => 'District of North Dakota',
    ),
    'tax' =>
    array (
      'title' => 'Tax Division',
    ),
    'usao-mdal' =>
    array (
      'title' => 'Middle District of Alabama',
    ),
    'usao-mdga' =>
    array (
      'title' => 'Middle District of Georgia',
    ),
    'usao-dc' =>
    array (
      'title' => 'District of District of Columbia',
    ),
    'usao-sdil' =>
    array (
      'title' => 'Southern District of Illinois',
    ),
    'usao-sdia' =>
    array (
      'title' => 'Southern District of Iowa',
    ),
    'usao-ut' =>
    array (
      'title' => 'District of Utah',
    ),
    'usao-edtx' =>
    array (
      'title' => 'Eastern District of Texas',
    ),
    'usao-edok' =>
    array (
      'title' => 'Eastern District of Oklahoma',
    ),
    'usao-wdnc' =>
    array (
      'title' => 'Western District of North Carolina',
    ),
    'usao-ndia' =>
    array (
      'title' => 'Northern District of Iowa',
    ),
    'usao-ndoh' =>
    array (
      'title' => 'Northern District of Ohio',
    ),
    'usao-hi' =>
    array (
      'title' => 'District of Hawaii',
    ),
    'usao-edky' =>
    array (
      'title' => 'Eastern District of Kentucky',
    ),
    'usao-sdfl' =>
    array (
      'title' => 'Southern District of Florida',
    ),
    'usao-sdfl-creole' =>
    array (
      'title' => 'Southern District of Florida Creole',
    ),
    'usao-sdfl-espanol' =>
    array (
      'title' => 'Southern District of Florida Espanol',
    ),
    'usao-nj' =>
    array (
      'title' => 'District of New Jersey',
    ),
    'usao-edca' =>
    array (
      'title' => 'Eastern District of California',
    ),
    'usao-mdnc' =>
    array (
      'title' => 'Middle District of North Carolina',
    ),
    'usao-mdtn' =>
    array (
      'title' => 'Middle District of Tennessee',
    ),
    'usao-edva' =>
    array (
      'title' => 'Eastern District of Virginia',
    ),
    'usao-ct' =>
    array (
      'title' => 'District of Connecticut',
    ),
    'usao-edca-espanol' =>
    array (
      'title' => 'Eastern District of California Espanol',
    ),
    'usao-edmo' =>
    array (
      'title' => 'Eastern District of Missouri',
    ),
    'usao-edmi' =>
    array (
      'title' => 'Eastern District of Michigan',
    ),
    'usao-mdpa' =>
    array (
      'title' => 'Middle District of Pennsylvania',
    ),
    'usao-mn' =>
    array (
      'title' => 'District of Minnesota',
    ),
    'usao-edtn' =>
    array (
      'title' => 'Eastern District of Tennessee',
    ),
    'enrd' =>
    array (
      'title' => 'Environment and Natural Resources Division',
    ),
    'ust' =>
    array (
      'title' => 'U.S. Trustee Program',
    ),
    'usao-wdtn' =>
    array (
      'title' => 'Western District of Tennessee',
    ),
    'usao-ndal' =>
    array (
      'title' => 'Northern District of Alabama',
    ),
    'usao-sdtx' =>
    array (
      'title' => 'Southern District of Texas',
    ),
    'usao-wdva' =>
    array (
      'title' => 'Western District of Virginia',
    ),
    'usao-wdar' =>
    array (
      'title' => 'Western District of Arkansas',
    ),
    'usao-ndga' =>
    array (
      'title' => 'Northern District of Georgia',
    ),
    'usao-sdga' =>
    array (
      'title' => 'Southern District of Georgia',
    ),
    'usao-nh' =>
    array (
      'title' => 'District of New Hampshire',
    ),
    'usao-pr' =>
    array (
      'title' => 'District of Puerto Rico',
    ),
    'usao-ndin' =>
    array (
      'title' => 'Northern District of Indiana',
    ),
    'criminal-ceos' =>
    array (
      'title' => 'Child Exploitation and Obscenity Section',
    ),
    'criminal-icitap' =>
    array (
      'title' => 'International Criminal Investigative Training Assistance Program',
    ),
    'criminal-hrsp' =>
    array (
      'title' => 'Human Rights and Special Prosecutions Section',
    ),
    'criminal-ccips' =>
    array (
      'title' => 'Computer Crime & Intellectual Property Section',
    ),
    'usao-sdny' =>
    array (
      'title' => 'Southern District of New York',
    ),
    'criminal-afmls' =>
    array (
      'title' => 'Asset Forfeiture and Money Laundering Section Home',
    ),
    'criminal-opdat' =>
    array (
      'title' => 'Office of Overseas Prosecutorial Development Assistance and Training',
    ),
    'criminal-disasters' =>
    array (
      'title' => 'Disaster Fraud Task Force',
    ),
    'criminal-oilspill' =>
    array (
      'title' => 'Deepwater Horizon (BP) Oil-Spill Fraud',
    ),
    'criminal-ocgs' =>
    array (
      'title' => 'Organized Crime and Gang Section',
    ),
  ),
  'migrations' =>
  array (
    'DataJson' =>
    array (
      'group_name' => 'data',
      'class_name' => 'JusticeJsonToDatasetMigration',
    ),
    'Organization' =>
    array (
      'group_name' => 'core',
      'class_name' => 'OrganizationMigration',
    ),
    'UsaoDistrict' =>
    array (
      'group_name' => 'usao',
      'class_name' => 'UsaoDistrictMigration',
    ),
    'UsaoStaffProfile' =>
    array (
      'group_name' => 'usao',
      'class_name' => 'UsaoStaffProfileMigration',
    ),
    'UsaoFile' =>
    array (
      'group_name' => 'usao',
      'class_name' => 'UsaoFileMigration',
    ),
    'UsaoPage' =>
    array (
      'group_name' => 'usao',
      'class_name' => 'UsaoPageMigration',
    ),
    'UsaoMdlaFile' =>
    array (
      'group_name' => 'usao-mdla',
      'class_name' => 'UsaoMdlaFileMigration',
    ),
    'UsaoMdlaPage' =>
    array (
      'group_name' => 'usao-mdla',
      'class_name' => 'UsaoMdlaPageMigration',
    ),
    'UsaoMdlaPressRelease' =>
    array (
      'group_name' => 'usao-mdla',
      'class_name' => 'UsaoMdlaPressReleaseMigration',
    ),
    'EoirFile' =>
    array (
      'group_name' => 'eoir',
      'class_name' => 'EoirFileMigration',
    ),
    'EoirPage' =>
    array (
      'group_name' => 'eoir',
      'class_name' => 'EoirPageMigration',
    ),
    'EoirPressRelease' =>
    array (
      'group_name' => 'eoir',
      'class_name' => 'EoirPressReleaseMigration',
    ),
    'UsaoSdinFile' =>
    array (
      'group_name' => 'usao-sdin',
      'class_name' => 'UsaoSdinFileMigration',
    ),
    'UsaoSdinPage' =>
    array (
      'group_name' => 'usao-sdin',
      'class_name' => 'UsaoSdinPageMigration',
    ),
    'UsaoSdinPressRelease' =>
    array (
      'group_name' => 'usao-sdin',
      'class_name' => 'UsaoSdinPressReleaseMigration',
    ),
    'UsaoWdlaFile' =>
    array (
      'group_name' => 'usao-wdla',
      'class_name' => 'UsaoWdlaFileMigration',
    ),
    'UsaoWdlaPage' =>
    array (
      'group_name' => 'usao-wdla',
      'class_name' => 'UsaoWdlaPageMigration',
    ),
    'UsaoWdlaPressRelease' =>
    array (
      'group_name' => 'usao-wdla',
      'class_name' => 'UsaoWdlaPressReleaseMigration',
    ),
    'UsaoMdFile' =>
    array (
      'group_name' => 'usao-md',
      'class_name' => 'UsaoMdFileMigration',
    ),
    'UsaoMdPage' =>
    array (
      'group_name' => 'usao-md',
      'class_name' => 'UsaoMdPageMigration',
    ),
    'UsaoMdPressRelease' =>
    array (
      'group_name' => 'usao-md',
      'class_name' => 'UsaoMdPressReleaseMigration',
    ),
    'UsaoNdnyFile' =>
    array (
      'group_name' => 'usao-ndny',
      'class_name' => 'UsaoNdnyFileMigration',
    ),
    'UsaoNdnyPage' =>
    array (
      'group_name' => 'usao-ndny',
      'class_name' => 'UsaoNdnyPageMigration',
    ),
    'UsaoNdnyPressRelease' =>
    array (
      'group_name' => 'usao-ndny',
      'class_name' => 'UsaoNdnyPressReleaseMigration',
    ),
    'UsaoWdmiFile' =>
    array (
      'group_name' => 'usao-wdmi',
      'class_name' => 'UsaoWdmiFileMigration',
    ),
    'UsaoWdmiPage' =>
    array (
      'group_name' => 'usao-wdmi',
      'class_name' => 'UsaoWdmiPageMigration',
    ),
    'UsaoWdmiPressRelease' =>
    array (
      'group_name' => 'usao-wdmi',
      'class_name' => 'UsaoWdmiPressReleaseMigration',
    ),
    'UsaoWdwaFile' =>
    array (
      'group_name' => 'usao-wdwa',
      'class_name' => 'UsaoWdwaFileMigration',
    ),
    'UsaoWdwaPage' =>
    array (
      'group_name' => 'usao-wdwa',
      'class_name' => 'UsaoWdwaPageMigration',
    ),
    'UsaoWdwaPressRelease' =>
    array (
      'group_name' => 'usao-wdwa',
      'class_name' => 'UsaoWdwaPressReleaseMigration',
    ),
    'UsaoNdmsFile' =>
    array (
      'group_name' => 'usao-ndms',
      'class_name' => 'UsaoNdmsFileMigration',
    ),
    'UsaoNdmsPage' =>
    array (
      'group_name' => 'usao-ndms',
      'class_name' => 'UsaoNdmsPageMigration',
    ),
    'UsaoNdmsPressRelease' =>
    array (
      'group_name' => 'usao-ndms',
      'class_name' => 'UsaoNdmsPressReleaseMigration',
    ),
    'UsaoNvFile' =>
    array (
      'group_name' => 'usao-nv',
      'class_name' => 'UsaoNvFileMigration',
    ),
    'UsaoNvPage' =>
    array (
      'group_name' => 'usao-nv',
      'class_name' => 'UsaoNvPageMigration',
    ),
    'UsaoNvPressRelease' =>
    array (
      'group_name' => 'usao-nv',
      'class_name' => 'UsaoNvPressReleaseMigration',
    ),
    'UsaoNeFile' =>
    array (
      'group_name' => 'usao-ne',
      'class_name' => 'UsaoNeFileMigration',
    ),
    'UsaoNePage' =>
    array (
      'group_name' => 'usao-ne',
      'class_name' => 'UsaoNePageMigration',
    ),
    'UsaoNePressRelease' =>
    array (
      'group_name' => 'usao-ne',
      'class_name' => 'UsaoNePressReleaseMigration',
    ),
    'UsaoOrFile' =>
    array (
      'group_name' => 'usao-or',
      'class_name' => 'UsaoOrFileMigration',
    ),
    'UsaoOrPage' =>
    array (
      'group_name' => 'usao-or',
      'class_name' => 'UsaoOrPageMigration',
    ),
    'UsaoOrPressRelease' =>
    array (
      'group_name' => 'usao-or',
      'class_name' => 'UsaoOrPressReleaseMigration',
    ),
    'UsaoEdwaFile' =>
    array (
      'group_name' => 'usao-edwa',
      'class_name' => 'UsaoEdwaFileMigration',
    ),
    'UsaoEdwaPage' =>
    array (
      'group_name' => 'usao-edwa',
      'class_name' => 'UsaoEdwaPageMigration',
    ),
    'UsaoEdwaPressRelease' =>
    array (
      'group_name' => 'usao-edwa',
      'class_name' => 'UsaoEdwaPressReleaseMigration',
    ),
    'UsaoAkFile' =>
    array (
      'group_name' => 'usao-ak',
      'class_name' => 'UsaoAkFileMigration',
    ),
    'UsaoAkPage' =>
    array (
      'group_name' => 'usao-ak',
      'class_name' => 'UsaoAkPageMigration',
    ),
    'UsaoAkPressRelease' =>
    array (
      'group_name' => 'usao-ak',
      'class_name' => 'UsaoAkPressReleaseMigration',
    ),
    'UsaoNdFile' =>
    array (
      'group_name' => 'usao-nd',
      'class_name' => 'UsaoNdFileMigration',
    ),
    'UsaoNdPage' =>
    array (
      'group_name' => 'usao-nd',
      'class_name' => 'UsaoNdPageMigration',
    ),
    'UsaoNdPressRelease' =>
    array (
      'group_name' => 'usao-nd',
      'class_name' => 'UsaoNdPressReleaseMigration',
    ),
    'TaxFile' =>
    array (
      'group_name' => 'tax',
      'class_name' => 'TaxFileMigration',
    ),
    'TaxPage' =>
    array (
      'group_name' => 'tax',
      'class_name' => 'TaxPageMigration',
    ),
    'TaxPressRelease' =>
    array (
      'group_name' => 'tax',
      'class_name' => 'TaxPressReleaseMigration',
    ),
    'UsaoMdalFile' =>
    array (
      'group_name' => 'usao-mdal',
      'class_name' => 'UsaoMdalFileMigration',
    ),
    'UsaoMdalPage' =>
    array (
      'group_name' => 'usao-mdal',
      'class_name' => 'UsaoMdalPageMigration',
    ),
    'UsaoMdalPressRelease' =>
    array (
      'group_name' => 'usao-mdal',
      'class_name' => 'UsaoMdalPressReleaseMigration',
    ),
    'UsaoMdgaFile' =>
    array (
      'group_name' => 'usao-mdga',
      'class_name' => 'UsaoMdgaFileMigration',
    ),
    'UsaoMdgaPage' =>
    array (
      'group_name' => 'usao-mdga',
      'class_name' => 'UsaoMdgaPageMigration',
    ),
    'UsaoMdgaPressRelease' =>
    array (
      'group_name' => 'usao-mdga',
      'class_name' => 'UsaoMdgaPressReleaseMigration',
    ),
    'UsaoDcFile' =>
    array (
      'group_name' => 'usao-dc',
      'class_name' => 'UsaoDcFileMigration',
    ),
    'UsaoDcPage' =>
    array (
      'group_name' => 'usao-dc',
      'class_name' => 'UsaoDcPageMigration',
    ),
    'UsaoDcPressRelease' =>
    array (
      'group_name' => 'usao-dc',
      'class_name' => 'UsaoDcPressReleaseMigration',
    ),
    'UsaoSdilFile' =>
    array (
      'group_name' => 'usao-sdil',
      'class_name' => 'UsaoSdilFileMigration',
    ),
    'UsaoSdilPage' =>
    array (
      'group_name' => 'usao-sdil',
      'class_name' => 'UsaoSdilPageMigration',
    ),
    'UsaoSdilPressRelease' =>
    array (
      'group_name' => 'usao-sdil',
      'class_name' => 'UsaoSdilPressReleaseMigration',
    ),
    'UsaoSdiaFile' =>
    array (
      'group_name' => 'usao-sdia',
      'class_name' => 'UsaoSdiaFileMigration',
    ),
    'UsaoSdiaPage' =>
    array (
      'group_name' => 'usao-sdia',
      'class_name' => 'UsaoSdiaPageMigration',
    ),
    'UsaoSdiaPressRelease' =>
    array (
      'group_name' => 'usao-sdia',
      'class_name' => 'UsaoSdiaPressReleaseMigration',
    ),
    'UsaoUtFile' =>
    array (
      'group_name' => 'usao-ut',
      'class_name' => 'UsaoUtFileMigration',
    ),
    'UsaoUtPage' =>
    array (
      'group_name' => 'usao-ut',
      'class_name' => 'UsaoUtPageMigration',
    ),
    'UsaoUtPressRelease' =>
    array (
      'group_name' => 'usao-ut',
      'class_name' => 'UsaoUtPressReleaseMigration',
    ),
    'UsaoEdtxFile' =>
    array (
      'group_name' => 'usao-edtx',
      'class_name' => 'UsaoEdtxFileMigration',
    ),
    'UsaoEdtxPage' =>
    array (
      'group_name' => 'usao-edtx',
      'class_name' => 'UsaoEdtxPageMigration',
    ),
    'UsaoEdtxPressRelease' =>
    array (
      'group_name' => 'usao-edtx',
      'class_name' => 'UsaoEdtxPressReleaseMigration',
    ),
    'UsaoWdncFile' =>
    array (
      'group_name' => 'usao-wdnc',
      'class_name' => 'UsaoWdncFileMigration',
    ),
    'UsaoWdncPage' =>
    array (
      'group_name' => 'usao-wdnc',
      'class_name' => 'UsaoWdncPageMigration',
    ),
    'UsaoWdncPressRelease' =>
    array (
      'group_name' => 'usao-wdnc',
      'class_name' => 'UsaoWdncPressReleaseMigration',
    ),
    'UsaoEdokFile' =>
    array (
      'group_name' => 'usao-edok',
      'class_name' => 'UsaoEdokFileMigration',
    ),
    'UsaoEdokPage' =>
    array (
      'group_name' => 'usao-edok',
      'class_name' => 'UsaoEdokPageMigration',
    ),
    'UsaoEdokPressRelease' =>
    array (
      'group_name' => 'usao-edok',
      'class_name' => 'UsaoEdokPressReleaseMigration',
    ),
    'UsaoNdiaFile' =>
    array (
      'group_name' => 'usao-ndia',
      'class_name' => 'UsaoNdiaFileMigration',
    ),
    'UsaoNdiaPage' =>
    array (
      'group_name' => 'usao-ndia',
      'class_name' => 'UsaoNdiaPageMigration',
    ),
    'UsaoNdiaPressRelease' =>
    array (
      'group_name' => 'usao-ndia',
      'class_name' => 'UsaoNdiaPressReleaseMigration',
    ),
    'UsaoNdohFile' =>
    array (
      'group_name' => 'usao-ndoh',
      'class_name' => 'UsaoNdohFileMigration',
    ),
    'UsaoNdohPage' =>
    array (
      'group_name' => 'usao-ndoh',
      'class_name' => 'UsaoNdohPageMigration',
    ),
    'UsaoNdohPressRelease' =>
    array (
      'group_name' => 'usao-ndoh',
      'class_name' => 'UsaoNdohPressReleaseMigration',
    ),
    'UsaoHiFile' =>
    array (
      'group_name' => 'usao-hi',
      'class_name' => 'UsaoHiFileMigration',
    ),
    'UsaoHiPage' =>
    array (
      'group_name' => 'usao-hi',
      'class_name' => 'UsaoHiPageMigration',
    ),
    'UsaoHiPressRelease' =>
    array (
      'group_name' => 'usao-hi',
      'class_name' => 'UsaoHiPressReleaseMigration',
    ),
    'UsaoSdflFile' =>
    array (
      'group_name' => 'usao-sdfl',
      'class_name' => 'UsaoSdflFileMigration',
    ),
    'UsaoSdflPage' =>
    array (
      'group_name' => 'usao-sdfl',
      'class_name' => 'UsaoSdflPageMigration',
    ),
    'UsaoSdflPageEs' =>
    array (
      'group_name' => 'usao-sdfl',
      'class_name' => 'UsaoSdflPageEspanolMigration',
    ),
    'UsaoSdflPageHt' =>
    array (
      'group_name' => 'usao-sdfl',
      'class_name' => 'UsaoSdflPageCreoleMigration',
    ),
    'UsaoSdflPressRelease' =>
    array (
      'group_name' => 'usao-sdfl',
      'class_name' => 'UsaoSdflPressReleaseMigration',
    ),
    'UsaoEdkyFile' =>
    array (
      'group_name' => 'usao-edky',
      'class_name' => 'UsaoEdkyFileMigration',
    ),
    'UsaoEdkyPage' =>
    array (
      'group_name' => 'usao-edky',
      'class_name' => 'UsaoEdkyPageMigration',
    ),
    'UsaoEdkyPressRelease' =>
    array (
      'group_name' => 'usao-edky',
      'class_name' => 'UsaoEdkyPressReleaseMigration',
    ),
    'UsaoNjFile' =>
    array (
      'group_name' => 'usao-nj',
      'class_name' => 'UsaoNjFileMigration',
    ),
    'UsaoNjPage' =>
    array (
      'group_name' => 'usao-nj',
      'class_name' => 'UsaoNjPageMigration',
    ),
    'UsaoNjPressRelease' =>
    array (
      'group_name' => 'usao-nj',
      'class_name' => 'UsaoNjPressReleaseMigration',
    ),
    'AfpFile' =>
    array (
      'group_name' => 'afp',
      'class_name' => 'AfpFileMigration',
    ),
    'AfpPage' =>
    array (
      'group_name' => 'afp',
      'class_name' => 'AfpPageMigration',
    ),
    'UsaoEdcaFile' =>
    array (
      'group_name' => 'usao-edca',
      'class_name' => 'UsaoEdcaFileMigration',
    ),
    'UsaoEdcaPage' =>
    array (
      'group_name' => 'usao-edca',
      'class_name' => 'UsaoEdcaPageMigration',
    ),
    'UsaoEdcaPressRelease' =>
    array (
      'group_name' => 'usao-edca',
      'class_name' => 'UsaoEdcaPressReleaseMigration',
    ),
    'UsaoMdncFile' =>
    array (
      'group_name' => 'usao-mdnc',
      'class_name' => 'UsaoMdncFileMigration',
    ),
    'UsaoMdncPage' =>
    array (
      'group_name' => 'usao-mdnc',
      'class_name' => 'UsaoMdncPageMigration',
    ),
    'UsaoMdncPressRelease' =>
    array (
      'group_name' => 'usao-mdnc',
      'class_name' => 'UsaoMdncPressReleaseMigration',
    ),
    'UsaoMdtnFile' =>
    array (
      'group_name' => 'usao-mdtn',
      'class_name' => 'UsaoMdtnFileMigration',
    ),
    'UsaoMdtnPage' =>
    array (
      'group_name' => 'usao-mdtn',
      'class_name' => 'UsaoMdtnPageMigration',
    ),
    'UsaoMdtnPressRelease' =>
    array (
      'group_name' => 'usao-mdtn',
      'class_name' => 'UsaoMdtnPressReleaseMigration',
    ),
    'UsaoEdvaFile' =>
    array (
      'group_name' => 'usao-edva',
      'class_name' => 'UsaoEdvaFileMigration',
    ),
    'UsaoEdvaPage' =>
    array (
      'group_name' => 'usao-edva',
      'class_name' => 'UsaoEdvaPageMigration',
    ),
    'UsaoEdvaPressRelease' =>
    array (
      'group_name' => 'usao-edva',
      'class_name' => 'UsaoEdvaPressReleaseMigration',
    ),
    'AtrGallery' =>
    array (
      'group_name' => 'atr',
      'class_name' => 'AtrGalleryMigration',
    ),
    'AtrGalleryImages' =>
    array (
      'group_name' => 'atr',
      'class_name' => 'AtrGalleryImagesMigration',
    ),
    'UsaoCtFile' =>
    array (
      'group_name' => 'usao-ct',
      'class_name' => 'UsaoCtFileMigration',
    ),
    'UsaoCtPage' =>
    array (
      'group_name' => 'usao-ct',
      'class_name' => 'UsaoCtPageMigration',
    ),
    'UsaoCtPressRelease' =>
    array (
      'group_name' => 'usao-ct',
      'class_name' => 'UsaoCtPressReleaseMigration',
    ),
    'UsaoEdcaPageEspanol' =>
    array (
      'group_name' => 'usao-edca-espanol',
      'class_name' => 'UsaoEdcaPageEspanolMigration',
    ),
    'UsaoEdcaPressReleaseEspanol' =>
    array (
      'group_name' => 'usao-edca-espanol',
      'class_name' => 'UsaoEdcaPressReleaseEspanolMigration',
    ),
    'UsaoEdmoFile' =>
    array (
      'group_name' => 'usao-edmo',
      'class_name' => 'UsaoEdmoFileMigration',
    ),
    'UsaoEdmoPage' =>
    array (
      'group_name' => 'usao-edmo',
      'class_name' => 'UsaoEdmoPageMigration',
    ),
    'UsaoEdmoPressRelease' =>
    array (
      'group_name' => 'usao-edmo',
      'class_name' => 'UsaoEdmoPressReleaseMigration',
    ),
    'UsaoEdmiFile' =>
    array (
      'group_name' => 'usao-edmi',
      'class_name' => 'UsaoEdmiFileMigration',
    ),
    'UsaoEdmiPage' =>
    array (
      'group_name' => 'usao-edmi',
      'class_name' => 'UsaoEdmiPageMigration',
    ),
    'UsaoEdmiPressRelease' =>
    array (
      'group_name' => 'usao-edmi',
      'class_name' => 'UsaoEdmiPressReleaseMigration',
    ),
    'UsaoMdpaFile' =>
    array (
      'group_name' => 'usao-mdpa',
      'class_name' => 'UsaoMdpaFileMigration',
    ),
    'UsaoMdpaPage' =>
    array (
      'group_name' => 'usao-mdpa',
      'class_name' => 'UsaoMdpaPageMigration',
    ),
    'UsaoMdpaPressRelease' =>
    array (
      'group_name' => 'usao-mdpa',
      'class_name' => 'UsaoMdpaPressReleaseMigration',
    ),
    'UsaoMdpaVwPressRelease' =>
    array (
      'group_name' => 'usao-mdpa',
      'class_name' => 'UsaoMdpaVwPressReleaseMigration',
    ),
    'UsaoMnFile' =>
    array (
      'group_name' => 'usao-mn',
      'class_name' => 'UsaoMnFileMigration',
    ),
    'UsaoMnPage' =>
    array (
      'group_name' => 'usao-mn',
      'class_name' => 'UsaoMnPageMigration',
    ),
    'UsaoMnPressRelease' =>
    array (
      'group_name' => 'usao-mn',
      'class_name' => 'UsaoMnPressReleaseMigration',
    ),
    'UsaoEdtnFile' =>
    array (
      'group_name' => 'usao-edtn',
      'class_name' => 'UsaoEdtnFileMigration',
    ),
    'UsaoEdtnPage' =>
    array (
      'group_name' => 'usao-edtn',
      'class_name' => 'UsaoEdtnPageMigration',
    ),
    'UsaoEdtnPressRelease' =>
    array (
      'group_name' => 'usao-edtn',
      'class_name' => 'UsaoEdtnPressReleaseMigration',
    ),
    'EnrdFile' =>
    array (
      'group_name' => 'enrd',
      'class_name' => 'EnrdFileMigration',
    ),
    'EnrdPage' =>
    array (
      'group_name' => 'enrd',
      'class_name' => 'EnrdPageMigration',
    ),
    'EnrdPressRelease' =>
    array (
      'group_name' => 'enrd',
      'class_name' => 'EnrdPressReleaseMigration',
    ),
    'EnrdTimeline' =>
    array (
      'group_name' => 'enrd',
      'class_name' => 'EnrdTimelineMigration',
    ),
    'EnrdEvent' =>
    array (
      'group_name' => 'enrd',
      'class_name' => 'EnrdEventMigration',
    ),
    'AtrPage' =>
    array (
      'group_name' => 'atr',
      'class_name' => 'AtrPageMigration',
    ),
    'AtrFile' =>
    array (
      'group_name' => 'atr',
      'class_name' => 'AtrFileMigration',
    ),
    'AtrPressRelease' =>
    array (
      'group_name' => 'atr',
      'class_name' => 'AtrPressReleaseMigration',
    ),
    'UstRegion' =>
    array (
      'group_name' => 'ust-regions',
      'class_name' => 'UstRegionMigration',
    ),
    'UstRegionsPage' =>
    array (
      'group_name' => 'ust-regions',
      'class_name' => 'UstRegionsPageMigration',
    ),
    'UstRegionsFile' =>
    array (
      'group_name' => 'ust-regions',
      'class_name' => 'UstRegionsFileMigration',
    ),
    'UstFile' =>
    array (
      'group_name' => 'ust',
      'class_name' => 'UstFileMigration',
    ),
    'UstPage' =>
    array (
      'group_name' => 'ust',
      'class_name' => 'UstPageMigration',
    ),
    'UstPressRelease' =>
    array (
      'group_name' => 'ust',
      'class_name' => 'UstPressReleaseMigration',
    ),
    'UsaoWdtnPage' =>
    array (
      'group_name' => 'usao-wdtn',
      'class_name' => 'UsaoWdtnPageMigration',
    ),
    'UsaoWdtnFile' =>
    array (
      'group_name' => 'usao-wdtn',
      'class_name' => 'UsaoWdtnFileMigration',
    ),
    'UsaoWdtnPressRelease' =>
    array (
      'group_name' => 'usao-wdtn',
      'class_name' => 'UsaoWdtnPressReleaseMigration',
    ),
    'UsaoNdalPage' =>
    array (
      'group_name' => 'usao-ndal',
      'class_name' => 'UsaoNdalPageMigration',
    ),
    'UsaoNdalFile' =>
    array (
      'group_name' => 'usao-ndal',
      'class_name' => 'UsaoNdalFileMigration',
    ),
    'UsaoNdalPressRelease' =>
    array (
      'group_name' => 'usao-ndal',
      'class_name' => 'UsaoNdalPressReleaseMigration',
    ),
    'UsaoSdtxFile' =>
    array (
      'group_name' => 'usao-sdtx',
      'class_name' => 'UsaoSdtxFileMigration',
    ),
    'UsaoSdtxPage' =>
    array (
      'group_name' => 'usao-sdtx',
      'class_name' => 'UsaoSdtxPageMigration',
    ),
    'UsaoSdtxPressRelease' =>
    array (
      'group_name' => 'usao-sdtx',
      'class_name' => 'UsaoSdtxPressReleaseMigration',
    ),
    'UsaoWdvaPage' =>
    array (
      'group_name' => 'usao-wdva',
      'class_name' => 'UsaoWdvaPageMigration',
    ),
    'UsaoWdvaFile' =>
    array (
      'group_name' => 'usao-wdva',
      'class_name' => 'UsaoWdvaFileMigration',
    ),
    'UsaoWdvaPressRelease' =>
    array (
      'group_name' => 'usao-wdva',
      'class_name' => 'UsaoWdvaPressReleaseMigration',
    ),
    'UsaoWdarPage' =>
    array (
      'group_name' => 'usao-wdar',
      'class_name' => 'UsaoWdarPageMigration',
    ),
    'UsaoWdarFile' =>
    array (
      'group_name' => 'usao-wdar',
      'class_name' => 'UsaoWdarFileMigration',
    ),
    'UsaoWdarPressRelease' =>
    array (
      'group_name' => 'usao-wdar',
      'class_name' => 'UsaoWdarPressReleaseMigration',
    ),
    'UsaoNdgaPage' =>
    array (
      'group_name' => 'usao-ndga',
      'class_name' => 'UsaoNdgaPageMigration',
    ),
    'UsaoNdgaFile' =>
    array (
      'group_name' => 'usao-ndga',
      'class_name' => 'UsaoNdgaFileMigration',
    ),
    'UsaoNdgaPressRelease' =>
    array (
      'group_name' => 'usao-ndga',
      'class_name' => 'UsaoNdgaPressReleaseMigration',
    ),
    'UsaoSdgaPage' =>
    array (
      'group_name' => 'usao-sdga',
      'class_name' => 'UsaoSdgaPageMigration',
    ),
    'UsaoSdgaFile' =>
    array (
      'group_name' => 'usao-sdga',
      'class_name' => 'UsaoSdgaFileMigration',
    ),
    'UsaoSdgaPressRelease' =>
    array (
      'group_name' => 'usao-sdga',
      'class_name' => 'UsaoSdgaPressReleaseMigration',
    ),
    'UsaoNhPage' =>
    array (
      'group_name' => 'usao-nh',
      'class_name' => 'UsaoNhPageMigration',
    ),
    'UsaoNhFile' =>
    array (
      'group_name' => 'usao-nh',
      'class_name' => 'UsaoNhFileMigration',
    ),
    'UsaoNhPressRelease' =>
    array (
      'group_name' => 'usao-nh',
      'class_name' => 'UsaoNhPressReleaseMigration',
    ),
    'UsaoPrPage' =>
    array (
      'group_name' => 'usao-pr',
      'class_name' => 'UsaoPrPageMigration',
    ),
    'UsaoPrFile' =>
    array (
      'group_name' => 'usao-pr',
      'class_name' => 'UsaoPrFileMigration',
    ),
    'UsaoPrPressRelease' =>
    array (
      'group_name' => 'usao-pr',
      'class_name' => 'UsaoPrPressReleaseMigration',
    ),
    'UsaoNdinPage' =>
    array (
      'group_name' => 'usao-ndin',
      'class_name' => 'UsaoNdinPageMigration',
    ),
    'UsaoNdinFile' =>
    array (
      'group_name' => 'usao-ndin',
      'class_name' => 'UsaoNdinFileMigration',
    ),
    'UsaoNdinPressRelease' =>
    array (
      'group_name' => 'usao-ndin',
      'class_name' => 'UsaoNdinPressReleaseMigration',
    ),
    'CriminalCeosPage' =>
    array (
      'group_name' => 'criminal-ceos',
      'class_name' => 'CriminalCeosPageMigration',
    ),
    'CriminalCeosFile' =>
    array (
      'group_name' => 'criminal-ceos',
      'class_name' => 'CriminalCeosFileMigration',
    ),
    'CriminalIcitapPage' =>
    array (
      'group_name' => 'criminal-icitap',
      'class_name' => 'CriminalIcitapPageMigration',
    ),
    'CriminalIcitapFile' =>
    array (
      'group_name' => 'criminal-icitap',
      'class_name' => 'CriminalIcitapFileMigration',
    ),
    'CriminalHrspPage' =>
    array (
      'group_name' => 'criminal-hrsp',
      'class_name' => 'CriminalHrspPageMigration',
    ),
    'CriminalHrspFile' =>
    array (
      'group_name' => 'criminal-hrsp',
      'class_name' => 'CriminalHrspFileMigration',
    ),
    'CriminalCcipsPage' =>
    array (
      'group_name' => 'criminal-ccips',
      'class_name' => 'CriminalCcipsPageMigration',
    ),
    'CriminalCcipsFile' =>
    array (
      'group_name' => 'criminal-ccips',
      'class_name' => 'CriminalCcipsFileMigration',
    ),
    'UsaoSdnyPage' =>
    array (
      'group_name' => 'usao-sdny',
      'class_name' => 'UsaoSdnyPageMigration',
    ),
    'UsaoSdnyFile' =>
    array (
      'group_name' => 'usao-sdny',
      'class_name' => 'UsaoSdnyFileMigration',
    ),
    'UsaoSdnyPressRelease' =>
    array (
      'group_name' => 'usao-sdny',
      'class_name' => 'UsaoSdnyPressReleaseMigration',
    ),
    'UsaoSdnySpeech' =>
    array (
      'group_name' => 'usao-sdny',
      'class_name' => 'UsaoSdnySpeechMigration',
    ),
    'CriminalAfmlsPage' =>
    array (
      'group_name' => 'criminal-afmls',
      'class_name' => 'CriminalAfmlsPageMigration',
    ),
    'CriminalAfmlsFile' =>
    array (
      'group_name' => 'criminal-afmls',
      'class_name' => 'CriminalAfmlsFileMigration',
    ),
    'CriminalOpdatPage' =>
    array (
      'group_name' => 'criminal-opdat',
      'class_name' => 'CriminalOpdatPageMigration',
    ),
    'CriminalOpdatFile' =>
    array (
      'group_name' => 'criminal-opdat',
      'class_name' => 'CriminalOpdatFileMigration',
    ),
    'CriminalDisastersPage' =>
    array (
      'group_name' => 'criminal-disasters',
      'class_name' => 'CriminalDisastersPageMigration',
    ),
    'CriminalDisastersFile' =>
    array (
      'group_name' => 'criminal-disasters',
      'class_name' => 'CriminalDisastersFileMigration',
    ),
    'CriminalOilspillPage' =>
    array (
      'group_name' => 'criminal-oilspill',
      'class_name' => 'CriminalOilspillPageMigration',
    ),
    'CriminalOilspillFile' =>
    array (
      'group_name' => 'criminal-oilspill',
      'class_name' => 'CriminalOilspillFileMigration',
    ),
    'CriminalOcgsPage' =>
    array (
      'group_name' => 'criminal-ocgs',
      'class_name' => 'CriminalOcgsPageMigration',
    ),
    'CriminalOcgsFile' =>
    array (
      'group_name' => 'criminal-ocgs',
      'class_name' => 'CriminalOcgsFileMigration',
    ),
  ),
);
// @codingStandardsIgnoreEnd
