<?php
/**
 * @file
 * Migrations.
 */

// @codingStandardsIgnoreStart
return array (
  'api' => 2,
  'groups' =>
  array (
    'core' =>
    array (
      'title' => 'Core Entities',
    ),
    'doj' =>
    array (
      'title' => 'DOJ - Department of Justice',
    ),
    'afp' =>
    array (
      'title' => 'Asset Forfeiture Program',
    ),
    'atr' =>
    array (
      'title' => 'Antitrust Division',
    ),
    'atr-espanol' =>
    array (
      'title' => 'División Antimonopolios en español',
    ),
    'eousa' =>
    array (
      'title' => 'EOUSA - Executive Office for United States Attorneys',
    ),
    'espanol' =>
    array (
      'title' => 'espanol - Justice.gov en Espanol',
    ),
    'nsd-ovt' =>
    array (
      'title' => 'NSD OVT - National Security Division Office of Justice for Victims of Overseas Terrorism',
    ),
    'ola' =>
    array (
      'title' => 'OLA - Office of Legislative Affairs',
    ),
    'usao-az' =>
    array (
      'title' => 'District of Arizona',
    ),
    'usao' =>
    array (
      'title' => 'USAO - United States Attorneys Office',
    ),
    'usao-espanol' =>
    array (
      'title' => 'USAO Espanol - Fiscales Federales',
    ),
    'usao-edla' =>
    array (
      'title' => 'Eastern District of Louisiana',
    ),
    'usao-edpa' =>
    array (
      'title' => 'Eastern District of Pennsylvania',
    ),
    'usao-gu' =>
    array (
      'title' => 'District of Guam & Northern Mariana Islands',
    ),
    'usao-id' =>
    array (
      'title' => 'District of Idaho',
    ),
    'usao-ks' =>
    array (
      'title' => 'District of Kansas',
    ),
    'usao-mt' =>
    array (
      'title' => 'District of Montana',
    ),
    'usao-ndca' =>
    array (
      'title' => 'Northern District of California',
    ),
    'usao-ndwv' =>
    array (
      'title' => 'Northern District of West Virginia',
    ),
    'usao-wdny' =>
    array (
      'title' => 'Western District of New York',
    ),
    'usao-wdok' =>
    array (
      'title' => 'Western District of Oklahoma',
    ),
    'usao-wdtx' =>
    array (
      'title' => 'Western District of Texas',
    ),
    'usao-wdky' =>
    array (
      'title' => 'Western District of Kentucky',
    ),
    'usao-wdmo' =>
    array (
      'title' => 'Western District of Missouri',
    ),
    'usao-sdwv' =>
    array (
      'title' => 'Southern District of West Virginia',
    ),
    'usao-ma' =>
    array (
      'title' => 'District of Massachusetts',
    ),
    'usao-mdla' =>
    array (
      'title' => 'Middle District of Louisiana',
    ),
    'usao-sdms' =>
    array (
      'title' => 'Southern District of Mississippi',
    ),
    'ust-regions' =>
    array (
      'title' => 'U.S. Trustee Program Regions and Offices',
    ),
    'pardon' =>
    array (
      'title' => 'Office of the Pardon',
    ),
    'uspc' =>
    array (
      'title' => 'U.S. Parole Commission',
    ),
    'eoir' =>
    array (
      'title' => 'Executive Office for Immigration Review',
    ),
    'mii' =>
    array (
      'title' => 'Medical Integrity Institute',
    ),
    'usao-sdal' =>
    array (
      'title' => 'Southern District of Alabama',
    ),
    'usao-ndfl' =>
    array (
      'title' => 'Northern District of Florida',
    ),
    'usao-mdfl' =>
    array (
      'title' => 'Middle District of Florida',
    ),
    'usao-sdin' =>
    array (
      'title' => 'Southern District of Indiana',
    ),
    'usao-wdla' =>
    array (
      'title' => 'Western District of Louisiana',
    ),
    'usao-md' =>
    array (
      'title' => 'District of Maryland',
    ),
    'usao-nm' =>
    array (
      'title' => 'District of New Mexico',
    ),
    'usao-ndny' =>
    array (
      'title' => 'Northern District of New York',
    ),
    'usao-me' =>
    array (
      'title' => 'District of Maine',
    ),
    'usao-sc' =>
    array (
      'title' => 'District of South Carolina',
    ),
    'usao-wdmi' =>
    array (
      'title' => 'Western District of Michigan',
    ),
    'usao-ndms' =>
    array (
      'title' => 'Northern District of Mississippi',
    ),
    'usao-wdwa' =>
    array (
      'title' => 'Western District of Washington',
    ),
    'usao-nv' =>
    array (
      'title' => 'District of Nevada',
    ),
    'usao-ne' =>
    array (
      'title' => 'District of Nebraska',
    ),
    'usao-or' =>
    array (
      'title' => 'District of Oregon',
    ),
    'usao-edwa' =>
    array (
      'title' => 'Eastern District of Washington',
    ),
    'usao-edwi' =>
    array (
      'title' => 'Eastern District of Wisconsin',
    ),
    'usao-ak' =>
    array (
      'title' => 'District of Alaska',
    ),
    'usao-nd' =>
    array (
      'title' => 'District of North Dakota',
    ),
    'tax' =>
    array (
      'title' => 'Tax Division',
    ),
    'usao-mdal' =>
    array (
      'title' => 'Middle District of Alabama',
    ),
    'opr' =>
    array (
      'title' => 'Office of Professional Responsibility',
    ),
    'usao-mdga' =>
    array (
      'title' => 'Middle District of Georgia',
    ),
    'usao-dc' =>
    array (
      'title' => 'District of District of Columbia',
    ),
    'usao-sdil' =>
    array (
      'title' => 'Southern District of Illinois',
    ),
    'usao-sdia' =>
    array (
      'title' => 'Southern District of Iowa',
    ),
    'usao-ut' =>
    array (
      'title' => 'District of Utah',
    ),
    'usao-edtx' =>
    array (
      'title' => 'Eastern District of Texas',
    ),
    'usao-edok' =>
    array (
      'title' => 'Eastern District of Oklahoma',
    ),
    'usao-wdnc' =>
    array (
      'title' => 'Western District of North Carolina',
    ),
    'usao-ndia' =>
    array (
      'title' => 'Northern District of Iowa',
    ),
    'usao-ndoh' =>
    array (
      'title' => 'Northern District of Ohio',
    ),
    'usao-hi' =>
    array (
      'title' => 'District of Hawaii',
    ),
    'usao-edky' =>
    array (
      'title' => 'Eastern District of Kentucky',
    ),
    'usao-sdfl' =>
    array (
      'title' => 'Southern District of Florida',
    ),
    'usao-sdfl-creole' =>
    array (
      'title' => 'Southern District of Florida Creole',
    ),
    'usao-sdfl-espanol' =>
    array (
      'title' => 'Southern District of Florida Espanol',
    ),
    'usao-nj' =>
    array (
      'title' => 'District of New Jersey',
    ),
    'usao-edca' =>
    array (
      'title' => 'Eastern District of California',
    ),
    'usao-mdnc' =>
    array (
      'title' => 'Middle District of North Carolina',
    ),
    'usao-mdtn' =>
    array (
      'title' => 'Middle District of Tennessee',
    ),
    'usao-edva' =>
    array (
      'title' => 'Eastern District of Virginia',
    ),
    'usao-ct' =>
    array (
      'title' => 'District of Connecticut',
    ),
    'usao-edca-espanol' =>
    array (
      'title' => 'Eastern District of California Espanol',
    ),
    'usao-edmo' =>
    array (
      'title' => 'Eastern District of Missouri',
    ),
    'usao-edmi' =>
    array (
      'title' => 'Eastern District of Michigan',
    ),
    'usao-mdpa' =>
    array (
      'title' => 'Middle District of Pennsylvania',
    ),
    'usao-mn' =>
    array (
      'title' => 'District of Minnesota',
    ),
    'usao-edtn' =>
    array (
      'title' => 'Eastern District of Tennessee',
    ),
    'enrd' =>
    array (
      'title' => 'Environment and Natural Resources Division',
    ),
    'ust' =>
    array (
      'title' => 'U.S. Trustee Program',
    ),
  ),
  'migrations' =>
  array (
    'DataJson' =>
    array (
      'group_name' => 'data',
      'class_name' => 'JusticeJsonToDatasetMigration',
    ),
    'EspanolFile' =>
    array (
      'group_name' => 'espanol',
      'class_name' => 'EspanolFileMigration',
    ),
    'EspanolPage' =>
    array (
      'group_name' => 'espanol',
      'class_name' => 'EspanolPageMigration',
    ),
    'EspanolPressRelease' =>
    array (
      'group_name' => 'espanol',
      'class_name' => 'EspanolPressReleaseMigration',
    ),
    'EspanolSpeech' =>
    array (
      'group_name' => 'espanol',
      'class_name' => 'EspanolSpeechMigration',
    ),
    'Organization' =>
    array (
      'group_name' => 'core',
      'class_name' => 'OrganizationMigration',
    ),
    'OlaFile' =>
    array (
      'group_name' => 'ola',
      'class_name' => 'OlaFileMigration',
    ),
    'OlaPage' =>
    array (
      'group_name' => 'ola',
      'class_name' => 'OlaPageMigration',
    ),
    'OlaTestimony' =>
    array (
      'group_name' => 'ola',
      'class_name' => 'OlaTestimonyMigration',
    ),
    'OlaWitness' =>
    array (
      'group_name' => 'ola',
      'class_name' => 'OlaWitnessMigration',
    ),
    'OlaDbTestimony' =>
    array (
      'group_name' => 'ola',
      'class_name' => 'OlaDbTestimonyMigration',
    ),
    'OlaDbWitness' =>
    array (
      'group_name' => 'ola',
      'class_name' => 'OlaDbWitnessMigration',
    ),
    'NsdOvtPage' =>
    array (
      'group_name' => 'nsd-ovt',
      'class_name' => 'NsdOvtPageMigration',
    ),
    'NsdOvtFile' =>
    array (
      'group_name' => 'nsd-ovt',
      'class_name' => 'NsdOvtFileMigration',
    ),
    'UsaoAzFile' =>
    array (
      'group_name' => 'usao-az',
      'class_name' => 'UsaoAzFileMigration',
    ),
    'UsaoAzPage' =>
    array (
      'group_name' => 'usao-az',
      'class_name' => 'UsaoAZPageMigration',
    ),
    'UsaoAzPressRelease' =>
    array (
      'group_name' => 'usao-az',
      'class_name' => 'UsaoAzPressReleaseMigration',
    ),
    'UsaoDistrict' =>
    array (
      'group_name' => 'usao',
      'class_name' => 'UsaoDistrictMigration',
    ),
    'UsaoStaffProfile' =>
    array (
      'group_name' => 'usao',
      'class_name' => 'UsaoStaffProfileMigration',
    ),
    'UsaoFile' =>
    array (
      'group_name' => 'usao',
      'class_name' => 'UsaoFileMigration',
    ),
    'UsaoPage' =>
    array (
      'group_name' => 'usao',
      'class_name' => 'UsaoPageMigration',
    ),
    'UsaoEspanolFile' =>
    array (
      'group_name' => 'usao-espanol',
      'class_name' => 'UsaoEspanolFileMigration',
    ),
    'UsaoEspanolPage' =>
    array (
      'group_name' => 'usao-espanol',
      'class_name' => 'UsaoEspanolPageMigration',
    ),
    'UsaoEdlaFile' =>
    array (
      'group_name' => 'usao-edla',
      'class_name' => 'UsaoEdlaFileMigration',
    ),
    'UsaoEdlaPage' =>
    array (
      'group_name' => 'usao-edla',
      'class_name' => 'UsaoEdlaPageMigration',
    ),
    'UsaoEdlaPressRelease' =>
    array (
      'group_name' => 'usao-edla',
      'class_name' => 'UsaoEdlaPressReleaseMigration',
    ),
    'UsaoEdpaFile' =>
    array (
      'group_name' => 'usao-edpa',
      'class_name' => 'UsaoEdpaFileMigration',
    ),
    'UsaoEdpaPage' =>
    array (
      'group_name' => 'usao-edpa',
      'class_name' => 'UsaoEdpaPageMigration',
    ),
    'UsaoEdpaPressRelease' =>
    array (
      'group_name' => 'usao-edpa',
      'class_name' => 'UsaoEdpaPressReleaseMigration',
    ),
    'UsaoGuFile' =>
    array (
      'group_name' => 'usao-gu',
      'class_name' => 'UsaoGuFileMigration',
    ),
    'UsaoGuPage' =>
    array (
      'group_name' => 'usao-gu',
      'class_name' => 'UsaoGuPageMigration',
    ),
    'UsaoGuPressRelease' =>
    array (
      'group_name' => 'usao-gu',
      'class_name' => 'UsaoGuPressReleaseMigration',
    ),
    'UsaoIdFile' =>
    array (
      'group_name' => 'usao-id',
      'class_name' => 'UsaoIdFileMigration',
    ),
    'UsaoIdPage' =>
    array (
      'group_name' => 'usao-id',
      'class_name' => 'UsaoIdPageMigration',
    ),
    'UsaoIdPressRelease' =>
    array (
      'group_name' => 'usao-id',
      'class_name' => 'UsaoIdPressReleaseMigration',
    ),
    'UsaoKsFile' =>
    array (
      'group_name' => 'usao-ks',
      'class_name' => 'UsaoKsFileMigration',
    ),
    'UsaoKsPage' =>
    array (
      'group_name' => 'usao-ks',
      'class_name' => 'UsaoKsPageMigration',
    ),
    'UsaoKsPressRelease' =>
    array (
      'group_name' => 'usao-ks',
      'class_name' => 'UsaoKsPressReleaseMigration',
    ),
    'UsaoMtFile' =>
    array (
      'group_name' => 'usao-mt',
      'class_name' => 'UsaoMtFileMigration',
    ),
    'UsaoMtPage' =>
    array (
      'group_name' => 'usao-mt',
      'class_name' => 'UsaoMtPageMigration',
    ),
    'UsaoMtPressRelease' =>
    array (
      'group_name' => 'usao-mt',
      'class_name' => 'UsaoMtPressReleaseMigration',
    ),
    'UsaoNdcaFile' =>
    array (
      'group_name' => 'usao-ndca',
      'class_name' => 'UsaoNdcaFileMigration',
    ),
    'UsaoNdcaPage' =>
    array (
      'group_name' => 'usao-ndca',
      'class_name' => 'UsaoNdcaPageMigration',
    ),
    'UsaoNdcaPressRelease' =>
    array (
      'group_name' => 'usao-ndca',
      'class_name' => 'UsaoNdcaPressReleaseMigration',
    ),
    'UsaoNdwvFile' =>
    array (
      'group_name' => 'usao-ndwv',
      'class_name' => 'UsaoNdwvFileMigration',
    ),
    'UsaoNdwvPage' =>
    array (
      'group_name' => 'usao-ndwv',
      'class_name' => 'UsaoNdwvPageMigration',
    ),
    'UsaoNdwvPressRelease' =>
    array (
      'group_name' => 'usao-ndwv',
      'class_name' => 'UsaoNdwvPressReleaseMigration',
    ),
    'UsaoWdnyFile' =>
    array (
      'group_name' => 'usao-wdny',
      'class_name' => 'UsaoWdnyFileMigration',
    ),
    'UsaoWdnyPage' =>
    array (
      'group_name' => 'usao-wdny',
      'class_name' => 'UsaoWdnyPageMigration',
    ),
    'UsaoWdnyPressRelease' =>
    array (
      'group_name' => 'usao-wdny',
      'class_name' => 'UsaoWdnyPressReleaseMigration',
    ),
    'UsaoWdokFile' =>
    array (
      'group_name' => 'usao-wdok',
      'class_name' => 'UsaoWdokFileMigration',
    ),
    'UsaoWdokPage' =>
    array (
      'group_name' => 'usao-wdok',
      'class_name' => 'UsaoWdokPageMigration',
    ),
    'UsaoWdokPressRelease' =>
    array (
      'group_name' => 'usao-wdok',
      'class_name' => 'UsaoWdokPressReleaseMigration',
    ),
    'UsaoWdtxFile' =>
    array (
      'group_name' => 'usao-wdtx',
      'class_name' => 'UsaoWdtxFileMigration',
    ),
    'UsaoWdtxPage' =>
    array (
      'group_name' => 'usao-wdtx',
      'class_name' => 'UsaoWdtxPageMigration',
    ),
    'UsaoWdtxPressRelease' =>
    array (
      'group_name' => 'usao-wdtx',
      'class_name' => 'UsaoWdtxPressReleaseMigration',
    ),
    'UsaoWdkyFile' =>
    array (
      'group_name' => 'usao-wdky',
      'class_name' => 'UsaoWdkyFileMigration',
    ),
    'UsaoWdkyPage' =>
    array (
      'group_name' => 'usao-wdky',
      'class_name' => 'UsaoWdkyPageMigration',
    ),
    'UsaoWdkyPressRelease' =>
    array (
      'group_name' => 'usao-wdky',
      'class_name' => 'UsaoWdkyPressReleaseMigration',
    ),
    'UsaoWdmoFile' =>
    array (
      'group_name' => 'usao-wdmo',
      'class_name' => 'UsaoWdmoFileMigration',
    ),
    'UsaoWdmoPage' =>
    array (
      'group_name' => 'usao-wdmo',
      'class_name' => 'UsaoWdmoPageMigration',
    ),
    'UsaoWdmoPressRelease' =>
    array (
      'group_name' => 'usao-wdmo',
      'class_name' => 'UsaoWdmoPressReleaseMigration',
    ),
    'UsaoSdwvFile' =>
    array (
      'group_name' => 'usao-sdwv',
      'class_name' => 'UsaoSdwvFileMigration',
    ),
    'UsaoSdwvPage' =>
    array (
      'group_name' => 'usao-sdwv',
      'class_name' => 'UsaoSdwvPageMigration',
    ),
    'UsaoSdwvPressRelease' =>
    array (
      'group_name' => 'usao-sdwv',
      'class_name' => 'UsaoSdwvPressReleaseMigration',
    ),
    'UsaoMaFile' =>
    array (
      'group_name' => 'usao-ma',
      'class_name' => 'UsaoMaFileMigration',
    ),
    'UsaoMaPage' =>
    array (
      'group_name' => 'usao-ma',
      'class_name' => 'UsaoMaPageMigration',
    ),
    'UsaoMaPressRelease' =>
    array (
      'group_name' => 'usao-ma',
      'class_name' => 'UsaoMaPressReleaseMigration',
    ),
    'UsaoMdlaFile' =>
    array (
      'group_name' => 'usao-mdla',
      'class_name' => 'UsaoMdlaFileMigration',
    ),
    'UsaoMdlaPage' =>
    array (
      'group_name' => 'usao-mdla',
      'class_name' => 'UsaoMdlaPageMigration',
    ),
    'UsaoMdlaPressRelease' =>
    array (
      'group_name' => 'usao-mdla',
      'class_name' => 'UsaoMdlaPressReleaseMigration',
    ),
    'UsaoSdmsFile' =>
    array (
      'group_name' => 'usao-sdms',
      'class_name' => 'UsaoSdmsFileMigration',
    ),
    'UsaoSdmsPage' =>
    array (
      'group_name' => 'usao-sdms',
      'class_name' => 'UsaoSdmsPageMigration',
    ),
    'UsaoSdmsPressRelease' =>
    array (
      'group_name' => 'usao-sdms',
      'class_name' => 'UsaoSdmsPressReleaseMigration',
    ),
    'PardonFile' =>
    array (
      'group_name' => 'pardon',
      'class_name' => 'PardonFileMigration',
    ),
    'PardonPage' =>
    array (
      'group_name' => 'pardon',
      'class_name' => 'PardonPageMigration',
    ),
    'UspcFile' =>
    array (
      'group_name' => 'uspc',
      'class_name' => 'UspcFileMigration',
    ),
    'UspcPage' =>
    array (
      'group_name' => 'uspc',
      'class_name' => 'UspcPageMigration',
    ),
    'EoirFile' =>
    array (
      'group_name' => 'eoir',
      'class_name' => 'EoirFileMigration',
    ),
    'EoirPage' =>
    array (
      'group_name' => 'eoir',
      'class_name' => 'EoirPageMigration',
    ),
    'EoirPressRelease' =>
    array (
      'group_name' => 'eoir',
      'class_name' => 'EoirPressReleaseMigration',
    ),
    'MiiFile' =>
    array (
      'group_name' => 'mii',
      'class_name' => 'MiiFileMigration',
    ),
    'MiiPage' =>
    array (
      'group_name' => 'mii',
      'class_name' => 'MiiPageMigration',
    ),
    'UsaoSdalFile' =>
    array (
      'group_name' => 'usao-sdal',
      'class_name' => 'UsaoSdalFileMigration',
    ),
    'UsaoSdalPage' =>
    array (
      'group_name' => 'usao-sdal',
      'class_name' => 'UsaoSdalPageMigration',
    ),
    'UsaoSdalPressRelease' =>
    array (
      'group_name' => 'usao-sdal',
      'class_name' => 'UsaoSdalPressReleaseMigration',
    ),
    'UsaoNdflFile' =>
    array (
      'group_name' => 'usao-ndfl',
      'class_name' => 'UsaoNdflFileMigration',
    ),
    'UsaoNdflPage' =>
    array (
      'group_name' => 'usao-ndfl',
      'class_name' => 'UsaoNdflPageMigration',
    ),
    'UsaoNdflPressRelease' =>
    array (
      'group_name' => 'usao-ndfl',
      'class_name' => 'UsaoNdflPressReleaseMigration',
    ),
    'UsaoMdflFile' =>
    array (
      'group_name' => 'usao-mdfl',
      'class_name' => 'UsaoMdflFileMigration',
    ),
    'UsaoMdflPage' =>
    array (
      'group_name' => 'usao-mdfl',
      'class_name' => 'UsaoMdflPageMigration',
    ),
    'UsaoMdflPressRelease' =>
    array (
      'group_name' => 'usao-mdfl',
      'class_name' => 'UsaoMdflPressReleaseMigration',
    ),
    'UsaoSdinFile' =>
    array (
      'group_name' => 'usao-sdin',
      'class_name' => 'UsaoSdinFileMigration',
    ),
    'UsaoSdinPage' =>
    array (
      'group_name' => 'usao-sdin',
      'class_name' => 'UsaoSdinPageMigration',
    ),
    'UsaoSdinPressRelease' =>
    array (
      'group_name' => 'usao-sdin',
      'class_name' => 'UsaoSdinPressReleaseMigration',
    ),
    'UsaoWdlaFile' =>
    array (
      'group_name' => 'usao-wdla',
      'class_name' => 'UsaoWdlaFileMigration',
    ),
    'UsaoWdlaPage' =>
    array (
      'group_name' => 'usao-wdla',
      'class_name' => 'UsaoWdlaPageMigration',
    ),
    'UsaoWdlaPressRelease' =>
    array (
      'group_name' => 'usao-wdla',
      'class_name' => 'UsaoWdlaPressReleaseMigration',
    ),
    'UsaoMdFile' =>
    array (
      'group_name' => 'usao-md',
      'class_name' => 'UsaoMdFileMigration',
    ),
    'UsaoMdPage' =>
    array (
      'group_name' => 'usao-md',
      'class_name' => 'UsaoMdPageMigration',
    ),
    'UsaoMdPressRelease' =>
    array (
      'group_name' => 'usao-md',
      'class_name' => 'UsaoMdPressReleaseMigration',
    ),
    'UsaoNmFile' =>
    array (
      'group_name' => 'usao-nm',
      'class_name' => 'UsaoNmFileMigration',
    ),
    'UsaoNmPage' =>
    array (
      'group_name' => 'usao-nm',
      'class_name' => 'UsaoNmPageMigration',
    ),
    'UsaoNmPressRelease' =>
    array (
      'group_name' => 'usao-nm',
      'class_name' => 'UsaoNmPressReleaseMigration',
    ),
    'UsaoNdnyFile' =>
    array (
      'group_name' => 'usao-ndny',
      'class_name' => 'UsaoNdnyFileMigration',
    ),
    'UsaoNdnyPage' =>
    array (
      'group_name' => 'usao-ndny',
      'class_name' => 'UsaoNdnyPageMigration',
    ),
    'UsaoNdnyPressRelease' =>
    array (
      'group_name' => 'usao-ndny',
      'class_name' => 'UsaoNdnyPressReleaseMigration',
    ),
    'UsaoMeFile' =>
    array (
      'group_name' => 'usao-me',
      'class_name' => 'UsaoMeFileMigration',
    ),
    'UsaoMePage' =>
    array (
      'group_name' => 'usao-me',
      'class_name' => 'UsaoMePageMigration',
    ),
    'UsaoMePressRelease' =>
    array (
      'group_name' => 'usao-me',
      'class_name' => 'UsaoMePressReleaseMigration',
    ),
    'UsaoScFile' =>
    array (
      'group_name' => 'usao-sc',
      'class_name' => 'UsaoScFileMigration',
    ),
    'UsaoScPage' =>
    array (
      'group_name' => 'usao-sc',
      'class_name' => 'UsaoScPageMigration',
    ),
    'UsaoScPressRelease' =>
    array (
      'group_name' => 'usao-sc',
      'class_name' => 'UsaoScPressReleaseMigration',
    ),
    'UsaoWdmiFile' =>
    array (
      'group_name' => 'usao-wdmi',
      'class_name' => 'UsaoWdmiFileMigration',
    ),
    'UsaoWdmiPage' =>
    array (
      'group_name' => 'usao-wdmi',
      'class_name' => 'UsaoWdmiPageMigration',
    ),
    'UsaoWdmiPressRelease' =>
    array (
      'group_name' => 'usao-wdmi',
      'class_name' => 'UsaoWdmiPressReleaseMigration',
    ),
    'UsaoWdwaFile' =>
    array (
      'group_name' => 'usao-wdwa',
      'class_name' => 'UsaoWdwaFileMigration',
    ),
    'UsaoWdwaPage' =>
    array (
      'group_name' => 'usao-wdwa',
      'class_name' => 'UsaoWdwaPageMigration',
    ),
    'UsaoWdwaPressRelease' =>
    array (
      'group_name' => 'usao-wdwa',
      'class_name' => 'UsaoWdwaPressReleaseMigration',
    ),
    'UsaoNdmsFile' =>
    array (
      'group_name' => 'usao-ndms',
      'class_name' => 'UsaoNdmsFileMigration',
    ),
    'UsaoNdmsPage' =>
    array (
      'group_name' => 'usao-ndms',
      'class_name' => 'UsaoNdmsPageMigration',
    ),
    'UsaoNdmsPressRelease' =>
    array (
      'group_name' => 'usao-ndms',
      'class_name' => 'UsaoNdmsPressReleaseMigration',
    ),
    'UsaoNvFile' =>
    array (
      'group_name' => 'usao-nv',
      'class_name' => 'UsaoNvFileMigration',
    ),
    'UsaoNvPage' =>
    array (
      'group_name' => 'usao-nv',
      'class_name' => 'UsaoNvPageMigration',
    ),
    'UsaoNvPressRelease' =>
    array (
      'group_name' => 'usao-nv',
      'class_name' => 'UsaoNvPressReleaseMigration',
    ),
    'UsaoNeFile' =>
    array (
      'group_name' => 'usao-ne',
      'class_name' => 'UsaoNeFileMigration',
    ),
    'UsaoNePage' =>
    array (
      'group_name' => 'usao-ne',
      'class_name' => 'UsaoNePageMigration',
    ),
    'UsaoNePressRelease' =>
    array (
      'group_name' => 'usao-ne',
      'class_name' => 'UsaoNePressReleaseMigration',
    ),
    'UsaoOrFile' =>
    array (
      'group_name' => 'usao-or',
      'class_name' => 'UsaoOrFileMigration',
    ),
    'UsaoOrPage' =>
    array (
      'group_name' => 'usao-or',
      'class_name' => 'UsaoOrPageMigration',
    ),
    'UsaoOrPressRelease' =>
    array (
      'group_name' => 'usao-or',
      'class_name' => 'UsaoOrPressReleaseMigration',
    ),
    'UsaoEdwaFile' =>
    array (
      'group_name' => 'usao-edwa',
      'class_name' => 'UsaoEdwaFileMigration',
    ),
    'UsaoEdwaPage' =>
    array (
      'group_name' => 'usao-edwa',
      'class_name' => 'UsaoEdwaPageMigration',
    ),
    'UsaoEdwaPressRelease' =>
    array (
      'group_name' => 'usao-edwa',
      'class_name' => 'UsaoEdwaPressReleaseMigration',
    ),
    'UsaoEdwiFile' =>
    array (
      'group_name' => 'usao-edwi',
      'class_name' => 'UsaoEdwiFileMigration',
    ),
    'UsaoEdwiPage' =>
    array (
      'group_name' => 'usao-edwi',
      'class_name' => 'UsaoEdwiPageMigration',
    ),
    'UsaoEdwiPressRelease' =>
    array (
      'group_name' => 'usao-edwi',
      'class_name' => 'UsaoEdwiPressReleaseMigration',
    ),
    'UsaoAkFile' =>
    array (
      'group_name' => 'usao-ak',
      'class_name' => 'UsaoAkFileMigration',
    ),
    'UsaoAkPage' =>
    array (
      'group_name' => 'usao-ak',
      'class_name' => 'UsaoAkPageMigration',
    ),
    'UsaoAkPressRelease' =>
    array (
      'group_name' => 'usao-ak',
      'class_name' => 'UsaoAkPressReleaseMigration',
    ),
    'UsaoNdFile' =>
    array (
      'group_name' => 'usao-nd',
      'class_name' => 'UsaoNdFileMigration',
    ),
    'UsaoNdPage' =>
    array (
      'group_name' => 'usao-nd',
      'class_name' => 'UsaoNdPageMigration',
    ),
    'UsaoNdPressRelease' =>
    array (
      'group_name' => 'usao-nd',
      'class_name' => 'UsaoNdPressReleaseMigration',
    ),
    'TaxFile' =>
    array (
      'group_name' => 'tax',
      'class_name' => 'TaxFileMigration',
    ),
    'TaxPage' =>
    array (
      'group_name' => 'tax',
      'class_name' => 'TaxPageMigration',
    ),
    'TaxPressRelease' =>
    array (
      'group_name' => 'tax',
      'class_name' => 'TaxPressReleaseMigration',
    ),
    'UsaoMdalFile' =>
    array (
      'group_name' => 'usao-mdal',
      'class_name' => 'UsaoMdalFileMigration',
    ),
    'UsaoMdalPage' =>
    array (
      'group_name' => 'usao-mdal',
      'class_name' => 'UsaoMdalPageMigration',
    ),
    'UsaoMdalPressRelease' =>
    array (
      'group_name' => 'usao-mdal',
      'class_name' => 'UsaoMdalPressReleaseMigration',
    ),
    'OprFile' =>
    array (
      'group_name' => 'opr',
      'class_name' => 'OprFileMigration',
    ),
    'OprPage' =>
    array (
      'group_name' => 'opr',
      'class_name' => 'OprPageMigration',
    ),
    'UsaoMdgaFile' =>
    array (
      'group_name' => 'usao-mdga',
      'class_name' => 'UsaoMdgaFileMigration',
    ),
    'UsaoMdgaPage' =>
    array (
      'group_name' => 'usao-mdga',
      'class_name' => 'UsaoMdgaPageMigration',
    ),
    'UsaoMdgaPressRelease' =>
    array (
      'group_name' => 'usao-mdga',
      'class_name' => 'UsaoMdgaPressReleaseMigration',
    ),
    'UsaoDcFile' =>
    array (
      'group_name' => 'usao-dc',
      'class_name' => 'UsaoDcFileMigration',
    ),
    'UsaoDcPage' =>
    array (
      'group_name' => 'usao-dc',
      'class_name' => 'UsaoDcPageMigration',
    ),
    'UsaoDcPressRelease' =>
    array (
      'group_name' => 'usao-dc',
      'class_name' => 'UsaoDcPressReleaseMigration',
    ),
    'UsaoSdilFile' =>
    array (
      'group_name' => 'usao-sdil',
      'class_name' => 'UsaoSdilFileMigration',
    ),
    'UsaoSdilPage' =>
    array (
      'group_name' => 'usao-sdil',
      'class_name' => 'UsaoSdilPageMigration',
    ),
    'UsaoSdilPressRelease' =>
    array (
      'group_name' => 'usao-sdil',
      'class_name' => 'UsaoSdilPressReleaseMigration',
    ),
    'UsaoSdiaFile' =>
    array (
      'group_name' => 'usao-sdia',
      'class_name' => 'UsaoSdiaFileMigration',
    ),
    'UsaoSdiaPage' =>
    array (
      'group_name' => 'usao-sdia',
      'class_name' => 'UsaoSdiaPageMigration',
    ),
    'UsaoSdiaPressRelease' =>
    array (
      'group_name' => 'usao-sdia',
      'class_name' => 'UsaoSdiaPressReleaseMigration',
    ),
    'UsaoUtFile' =>
    array (
      'group_name' => 'usao-ut',
      'class_name' => 'UsaoUtFileMigration',
    ),
    'UsaoUtPage' =>
    array (
      'group_name' => 'usao-ut',
      'class_name' => 'UsaoUtPageMigration',
    ),
    'UsaoUtPressRelease' =>
    array (
      'group_name' => 'usao-ut',
      'class_name' => 'UsaoUtPressReleaseMigration',
    ),
    'UsaoEdtxFile' =>
    array (
      'group_name' => 'usao-edtx',
      'class_name' => 'UsaoEdtxFileMigration',
    ),
    'UsaoEdtxPage' =>
    array (
      'group_name' => 'usao-edtx',
      'class_name' => 'UsaoEdtxPageMigration',
    ),
    'UsaoEdtxPressRelease' =>
    array (
      'group_name' => 'usao-edtx',
      'class_name' => 'UsaoEdtxPressReleaseMigration',
    ),
    'UsaoWdncFile' =>
    array (
      'group_name' => 'usao-wdnc',
      'class_name' => 'UsaoWdncFileMigration',
    ),
    'UsaoWdncPage' =>
    array (
      'group_name' => 'usao-wdnc',
      'class_name' => 'UsaoWdncPageMigration',
    ),
    'UsaoWdncPressRelease' =>
    array (
      'group_name' => 'usao-wdnc',
      'class_name' => 'UsaoWdncPressReleaseMigration',
    ),
    'UsaoEdokFile' =>
    array (
      'group_name' => 'usao-edok',
      'class_name' => 'UsaoEdokFileMigration',
    ),
    'UsaoEdokPage' =>
    array (
      'group_name' => 'usao-edok',
      'class_name' => 'UsaoEdokPageMigration',
    ),
    'UsaoEdokPressRelease' =>
    array (
      'group_name' => 'usao-edok',
      'class_name' => 'UsaoEdokPressReleaseMigration',
    ),
    'UsaoNdiaFile' =>
    array (
      'group_name' => 'usao-ndia',
      'class_name' => 'UsaoNdiaFileMigration',
    ),
    'UsaoNdiaPage' =>
    array (
      'group_name' => 'usao-ndia',
      'class_name' => 'UsaoNdiaPageMigration',
    ),
    'UsaoNdiaPressRelease' =>
    array (
      'group_name' => 'usao-ndia',
      'class_name' => 'UsaoNdiaPressReleaseMigration',
    ),
    'UsaoNdohFile' =>
    array (
      'group_name' => 'usao-ndoh',
      'class_name' => 'UsaoNdohFileMigration',
    ),
    'UsaoNdohPage' =>
    array (
      'group_name' => 'usao-ndoh',
      'class_name' => 'UsaoNdohPageMigration',
    ),
    'UsaoNdohPressRelease' =>
    array (
      'group_name' => 'usao-ndoh',
      'class_name' => 'UsaoNdohPressReleaseMigration',
    ),
    'UsaoHiFile' =>
    array (
      'group_name' => 'usao-hi',
      'class_name' => 'UsaoHiFileMigration',
    ),
    'UsaoHiPage' =>
    array (
      'group_name' => 'usao-hi',
      'class_name' => 'UsaoHiPageMigration',
    ),
    'UsaoHiPressRelease' =>
    array (
      'group_name' => 'usao-hi',
      'class_name' => 'UsaoHiPressReleaseMigration',
    ),
    'UsaoSdflFile' =>
    array (
      'group_name' => 'usao-sdfl',
      'class_name' => 'UsaoSdflFileMigration',
    ),
    'UsaoSdflPage' =>
    array (
      'group_name' => 'usao-sdfl',
      'class_name' => 'UsaoSdflPageMigration',
    ),
    'UsaoSdflPageEs' =>
    array (
      'group_name' => 'usao-sdfl',
      'class_name' => 'UsaoSdflPageEspanolMigration',
    ),
    'UsaoSdflPageHt' =>
    array (
      'group_name' => 'usao-sdfl',
      'class_name' => 'UsaoSdflPageCreoleMigration',
    ),
    'UsaoSdflPressRelease' =>
    array (
      'group_name' => 'usao-sdfl',
      'class_name' => 'UsaoSdflPressReleaseMigration',
    ),
    'UsaoEdkyFile' =>
    array (
      'group_name' => 'usao-edky',
      'class_name' => 'UsaoEdkyFileMigration',
    ),
    'UsaoEdkyPage' =>
    array (
      'group_name' => 'usao-edky',
      'class_name' => 'UsaoEdkyPageMigration',
    ),
    'UsaoEdkyPressRelease' =>
    array (
      'group_name' => 'usao-edky',
      'class_name' => 'UsaoEdkyPressReleaseMigration',
    ),
    'UsaoNjFile' =>
    array (
      'group_name' => 'usao-nj',
      'class_name' => 'UsaoNjFileMigration',
    ),
    'UsaoNjPage' =>
    array (
      'group_name' => 'usao-nj',
      'class_name' => 'UsaoNjPageMigration',
    ),
    'UsaoNjPressRelease' =>
    array (
      'group_name' => 'usao-nj',
      'class_name' => 'UsaoNjPressReleaseMigration',
    ),
    'AfpFile' =>
    array (
      'group_name' => 'afp',
      'class_name' => 'AfpFileMigration',
    ),
    'AfpPage' =>
    array (
      'group_name' => 'afp',
      'class_name' => 'AfpPageMigration',
    ),
    'UsaoEdcaFile' =>
    array (
      'group_name' => 'usao-edca',
      'class_name' => 'UsaoEdcaFileMigration',
    ),
    'UsaoEdcaPage' =>
    array (
      'group_name' => 'usao-edca',
      'class_name' => 'UsaoEdcaPageMigration',
    ),
    'UsaoEdcaPressRelease' =>
    array (
      'group_name' => 'usao-edca',
      'class_name' => 'UsaoEdcaPressReleaseMigration',
    ),
    'UsaoMdncFile' =>
    array (
      'group_name' => 'usao-mdnc',
      'class_name' => 'UsaoMdncFileMigration',
    ),
    'UsaoMdncPage' =>
    array (
      'group_name' => 'usao-mdnc',
      'class_name' => 'UsaoMdncPageMigration',
    ),
    'UsaoMdncPressRelease' =>
    array (
      'group_name' => 'usao-mdnc',
      'class_name' => 'UsaoMdncPressReleaseMigration',
    ),
    'UsaoMdtnFile' =>
    array (
      'group_name' => 'usao-mdtn',
      'class_name' => 'UsaoMdtnFileMigration',
    ),
    'UsaoMdtnPage' =>
    array (
      'group_name' => 'usao-mdtn',
      'class_name' => 'UsaoMdtnPageMigration',
    ),
    'UsaoMdtnPressRelease' =>
    array (
      'group_name' => 'usao-mdtn',
      'class_name' => 'UsaoMdtnPressReleaseMigration',
    ),
    'UsaoEdvaFile' =>
    array (
      'group_name' => 'usao-edva',
      'class_name' => 'UsaoEdvaFileMigration',
    ),
    'UsaoEdvaPage' =>
    array (
      'group_name' => 'usao-edva',
      'class_name' => 'UsaoEdvaPageMigration',
    ),
    'UsaoEdvaPressRelease' =>
    array (
      'group_name' => 'usao-edva',
      'class_name' => 'UsaoEdvaPressReleaseMigration',
    ),
    'AtrGallery' =>
    array (
      'group_name' => 'atr',
      'class_name' => 'AtrGalleryMigration',
    ),
    'AtrGalleryImages' =>
    array (
      'group_name' => 'atr',
      'class_name' => 'AtrGalleryImagesMigration',
    ),
    'UsaoCtFile' =>
    array (
      'group_name' => 'usao-ct',
      'class_name' => 'UsaoCtFileMigration',
    ),
    'UsaoCtPage' =>
    array (
      'group_name' => 'usao-ct',
      'class_name' => 'UsaoCtPageMigration',
    ),
    'UsaoCtPressRelease' =>
    array (
      'group_name' => 'usao-ct',
      'class_name' => 'UsaoCtPressReleaseMigration',
    ),
    'UsaoEdcaPageEspanol' =>
    array (
      'group_name' => 'usao-edca',
      'class_name' => 'UsaoEdcaPageEspanolMigration',
    ),
    'UsaoEdcaPressReleaseEspanol' =>
    array (
      'group_name' => 'usao-edca',
      'class_name' => 'UsaoEdcaPressReleaseEspanolMigration',
    ),
    'UsaoEdmoFile' =>
    array (
      'group_name' => 'usao-edmo',
      'class_name' => 'UsaoEdmoFileMigration',
    ),
    'UsaoEdmoPage' =>
    array (
      'group_name' => 'usao-edmo',
      'class_name' => 'UsaoEdmoPageMigration',
    ),
    'UsaoEdmoPressRelease' =>
    array (
      'group_name' => 'usao-edmo',
      'class_name' => 'UsaoEdmoPressReleaseMigration',
    ),
    'UsaoEdmiFile' =>
    array (
      'group_name' => 'usao-edmi',
      'class_name' => 'UsaoEdmiFileMigration',
    ),
    'UsaoEdmiPage' =>
    array (
      'group_name' => 'usao-edmi',
      'class_name' => 'UsaoEdmiPageMigration',
    ),
    'UsaoEdmiPressRelease' =>
    array (
      'group_name' => 'usao-edmi',
      'class_name' => 'UsaoEdmiPressReleaseMigration',
    ),
    'UsaoMdpaFile' =>
    array (
      'group_name' => 'usao-mdpa',
      'class_name' => 'UsaoMdpaFileMigration',
    ),
    'UsaoMdpaPage' =>
    array (
      'group_name' => 'usao-mdpa',
      'class_name' => 'UsaoMdpaPageMigration',
    ),
    'UsaoMdpaPressRelease' =>
    array (
      'group_name' => 'usao-mdpa',
      'class_name' => 'UsaoMdpaPressReleaseMigration',
    ),
    'UsaoMdpaVwPressRelease' =>
    array (
      'group_name' => 'usao-mdpa',
      'class_name' => 'UsaoMdpaVwPressReleaseMigration',
    ),
    'UsaoMnFile' =>
    array (
      'group_name' => 'usao-mn',
      'class_name' => 'UsaoMnFileMigration',
    ),
    'UsaoMnPage' =>
    array (
      'group_name' => 'usao-mn',
      'class_name' => 'UsaoMnPageMigration',
    ),
    'UsaoMnPressRelease' =>
    array (
      'group_name' => 'usao-mn',
      'class_name' => 'UsaoMnPressReleaseMigration',
    ),
    'UsaoEdtnFile' =>
    array (
      'group_name' => 'usao-edtn',
      'class_name' => 'UsaoEdtnFileMigration',
    ),
    'UsaoEdtnPage' =>
    array (
      'group_name' => 'usao-edtn',
      'class_name' => 'UsaoEdtnPageMigration',
    ),
    'UsaoEdtnPressRelease' =>
    array (
      'group_name' => 'usao-edtn',
      'class_name' => 'UsaoEdtnPressReleaseMigration',
    ),
    'EnrdFile' =>
    array (
      'group_name' => 'enrd',
      'class_name' => 'EnrdFileMigration',
    ),
    'EnrdPage' =>
    array (
      'group_name' => 'enrd',
      'class_name' => 'EnrdPageMigration',
    ),
    'EnrdPressRelease' =>
    array (
      'group_name' => 'enrd',
      'class_name' => 'EnrdPressReleaseMigration',
    ),
    'AtrPage' =>
    array (
      'group_name' => 'atr',
      'class_name' => 'AtrPageMigration',
    ),
    'AtrFile' =>
    array (
      'group_name' => 'atr',
      'class_name' => 'AtrFileMigration',
    ),
    'AtrPressRelease' =>
    array (
      'group_name' => 'atr',
      'class_name' => 'AtrPressReleaseMigration',
    ),
    'UstRegionsPage' =>
    array (
      'group_name' => 'ust-regions',
      'class_name' => 'UstRegionsPageMigration',
    ),
    'UstRegionsFile' =>
    array (
      'group_name' => 'ust-regions',
      'class_name' => 'UstRegionsFileMigration',
    ),
    'UstFile' =>
    array (
      'group_name' => 'ust',
      'class_name' => 'UstFileMigration',
    ),
    'UstPage' =>
    array (
      'group_name' => 'ust',
      'class_name' => 'UstPageMigration',
    ),
    'UstPressRelease' =>
    array (
      'group_name' => 'ust',
      'class_name' => 'UstPressReleaseMigration'
    ),
  ),
);
// @codingStandardsIgnoreEnd
